[package]
name = "mandrake-net"
description = "dladm/ipadm/Crossbow driver for Mandrake"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[dependencies]

[lints]
workspace = true
