[package]
name = "mandrake-bhyve"
description = "bhyve VM to zone-configuration mapping for Mandrake"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[dependencies]
mandrake-core = { workspace = true }
mandrake-zones = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
