//! Boot environments, updates, and host settings (ADR-0015), mirroring
//! the `system`, `boot-environments`, and `updates` tags in
//! `api/openapi.yaml`.

use std::fmt;

use serde::{Deserialize, Serialize};

use crate::{Id, Timestamp};

/// `GET /system/settings`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SystemSettings {
    /// Hostname.
    pub hostname: String,
    /// Timezone name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// NTP servers from chrony.conf.
    pub ntp_servers: Vec<String>,
}

/// `PATCH /system`.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct SystemUpdate {
    /// Hostname.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    /// Timezone name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Replaces the NTP servers; empty disables.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ntp_servers: Option<Vec<String>>,
}

/// `GET /system/tls`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TlsInfo {
    /// Subject.
    pub subject: String,
    /// Issuer.
    pub issuer: String,
    /// Valid from.
    pub not_before: Timestamp,
    /// Valid until.
    pub not_after: Timestamp,
    /// SHA-256 of the leaf, `AA:BB:...`.
    pub fingerprint: String,
    /// Generated by the daemon.
    pub self_signed: bool,
}

/// `PUT /system/tls`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TlsUpload {
    /// Leaf first, then intermediates.
    pub certificate_pem: String,
    /// The matching private key.
    pub key_pem: String,
}

/// A boot environment as `beadm` reports it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BootEnvironment {
    /// beadm's UUID.
    pub id: Id,
    /// Name.
    pub name: String,
    /// Boots next.
    pub active: bool,
    /// Running now.
    pub booted: bool,
    /// Mountpoint when mounted.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mountpoint: Option<String>,
    /// Space used.
    pub space_bytes: u64,
    /// libbe policy.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
    /// Created.
    pub created_at: Timestamp,
}

/// `POST /system/boot-environments`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BootEnvironmentCreate {
    /// Name.
    pub name: String,
}

/// `GET /system/boot-environments`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BootEnvironmentList {
    /// In beadm order.
    pub items: Vec<BootEnvironment>,
}

/// What `pkg` would do to one package.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum UpdateAction {
    /// New package.
    Install,
    /// Version change.
    Update,
    /// Removal.
    Remove,
}

impl fmt::Display for UpdateAction {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Install => "install",
            Self::Update => "update",
            Self::Remove => "remove",
        })
    }
}

/// One line of the plan.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UpdatePackage {
    /// FMRI stem.
    pub name: String,
    /// Action.
    pub action: UpdateAction,
    /// Version now.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub old_version: Option<String>,
    /// Version after.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub new_version: Option<String>,
}

/// The parsed dry run.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct UpdatePlan {
    /// Packages.
    pub packages: Vec<UpdatePackage>,
    /// Reboot needed.
    pub reboot_required: bool,
    /// BE the apply creates.
    pub boot_environment: String,
    /// Mandrake version after, when it changes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mandrake_version: Option<String>,
    /// When checked.
    pub checked_at: Timestamp,
    /// Unparsed text, when parsing failed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub raw: Option<String>,
}

impl UpdatePlan {
    /// Whether there is anything to apply.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.packages.is_empty() && self.raw.is_none()
    }
}

/// `GET /system/updates`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct UpdateState {
    /// Last plan.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub plan: Option<UpdatePlan>,
    /// A check job runs.
    pub checking: bool,
    /// An apply job runs.
    pub applying: bool,
    /// The running or last check job.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub check_job: Option<Id>,
    /// The running or last apply job.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub apply_job: Option<Id>,
    /// When the last apply finished.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub applied_at: Option<Timestamp>,
    /// The BE the last apply created.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub applied_boot_environment: Option<String>,
    /// The rollback target.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub previous_boot_environment: Option<String>,
}
